name: Businesses
version: '1.0'
main: org.crewco.businesses.SCBusinesses
api-version: '1.20'
depend: [Vault]
authors: [CarThax,XST99]

commands:
  business:
    description: General Business Command
    usage: /<command>
  businessadmin:
    description: General Business Admin Command
    usage: /<command>