name: SC-Business
version: '1.0'
main: org.crewco.SCBusinesses.SCBusinesses
api-version: '1.20'
depend: [Vault]
authors: [CarThax,XST99,William Bar]

commands:
  business:
    description: General Business Command
    usage: /<command>
  businessadmin:
    description: General Business Admin Command
    usage: /<command>